# frozen_string_literal: true

# Enumerations from gumbo-parser (tokenizer_states.h, token_type.h, insertion_mode.h, error.h,
# nokogiri_gumbo.h). Values must match the C enums.

module Nokogiri
  module Pure
    module Gumbo
      # GumboTokenizerEnum
      LEX_DATA = 0
      LEX_RCDATA = 1
      LEX_RAWTEXT = 2
      LEX_SCRIPT_DATA = 3
      LEX_PLAINTEXT = 4
      LEX_TAG_OPEN = 5
      LEX_END_TAG_OPEN = 6
      LEX_TAG_NAME = 7
      LEX_RCDATA_LT = 8
      LEX_RCDATA_END_TAG_OPEN = 9
      LEX_RCDATA_END_TAG_NAME = 10
      LEX_RAWTEXT_LT = 11
      LEX_RAWTEXT_END_TAG_OPEN = 12
      LEX_RAWTEXT_END_TAG_NAME = 13
      LEX_SCRIPT_DATA_LT = 14
      LEX_SCRIPT_DATA_END_TAG_OPEN = 15
      LEX_SCRIPT_DATA_END_TAG_NAME = 16
      LEX_SCRIPT_DATA_ESCAPED_START = 17
      LEX_SCRIPT_DATA_ESCAPED_START_DASH = 18
      LEX_SCRIPT_DATA_ESCAPED = 19
      LEX_SCRIPT_DATA_ESCAPED_DASH = 20
      LEX_SCRIPT_DATA_ESCAPED_DASH_DASH = 21
      LEX_SCRIPT_DATA_ESCAPED_LT = 22
      LEX_SCRIPT_DATA_ESCAPED_END_TAG_OPEN = 23
      LEX_SCRIPT_DATA_ESCAPED_END_TAG_NAME = 24
      LEX_SCRIPT_DATA_DOUBLE_ESCAPED_START = 25
      LEX_SCRIPT_DATA_DOUBLE_ESCAPED = 26
      LEX_SCRIPT_DATA_DOUBLE_ESCAPED_DASH = 27
      LEX_SCRIPT_DATA_DOUBLE_ESCAPED_DASH_DASH = 28
      LEX_SCRIPT_DATA_DOUBLE_ESCAPED_LT = 29
      LEX_SCRIPT_DATA_DOUBLE_ESCAPED_END = 30
      LEX_BEFORE_ATTR_NAME = 31
      LEX_ATTR_NAME = 32
      LEX_AFTER_ATTR_NAME = 33
      LEX_BEFORE_ATTR_VALUE = 34
      LEX_ATTR_VALUE_DOUBLE_QUOTED = 35
      LEX_ATTR_VALUE_SINGLE_QUOTED = 36
      LEX_ATTR_VALUE_UNQUOTED = 37
      LEX_AFTER_ATTR_VALUE_QUOTED = 38
      LEX_SELF_CLOSING_START_TAG = 39
      LEX_BOGUS_COMMENT = 40
      LEX_MARKUP_DECLARATION_OPEN = 41
      LEX_COMMENT_START = 42
      LEX_COMMENT_START_DASH = 43
      LEX_COMMENT = 44
      LEX_COMMENT_LT = 45
      LEX_COMMENT_LT_BANG = 46
      LEX_COMMENT_LT_BANG_DASH = 47
      LEX_COMMENT_LT_BANG_DASH_DASH = 48
      LEX_COMMENT_END_DASH = 49
      LEX_COMMENT_END = 50
      LEX_COMMENT_END_BANG = 51
      LEX_DOCTYPE = 52
      LEX_BEFORE_DOCTYPE_NAME = 53
      LEX_DOCTYPE_NAME = 54
      LEX_AFTER_DOCTYPE_NAME = 55
      LEX_AFTER_DOCTYPE_PUBLIC_KEYWORD = 56
      LEX_BEFORE_DOCTYPE_PUBLIC_ID = 57
      LEX_DOCTYPE_PUBLIC_ID_DOUBLE_QUOTED = 58
      LEX_DOCTYPE_PUBLIC_ID_SINGLE_QUOTED = 59
      LEX_AFTER_DOCTYPE_PUBLIC_ID = 60
      LEX_BETWEEN_DOCTYPE_PUBLIC_SYSTEM_ID = 61
      LEX_AFTER_DOCTYPE_SYSTEM_KEYWORD = 62
      LEX_BEFORE_DOCTYPE_SYSTEM_ID = 63
      LEX_DOCTYPE_SYSTEM_ID_DOUBLE_QUOTED = 64
      LEX_DOCTYPE_SYSTEM_ID_SINGLE_QUOTED = 65
      LEX_AFTER_DOCTYPE_SYSTEM_ID = 66
      LEX_BOGUS_DOCTYPE = 67
      LEX_CDATA_SECTION = 68
      LEX_CDATA_SECTION_BRACKET = 69
      LEX_CDATA_SECTION_END = 70
      LEX_CHARACTER_REFERENCE = 71
      LEX_NAMED_CHARACTER_REFERENCE = 72
      LEX_AMBIGUOUS_AMPERSAND = 73
      LEX_NUMERIC_CHARACTER_REFERENCE = 74
      LEX_HEXADECIMAL_CHARACTER_REFERENCE_START = 75
      LEX_DECIMAL_CHARACTER_REFERENCE_START = 76
      LEX_HEXADECIMAL_CHARACTER_REFERENCE = 77
      LEX_DECIMAL_CHARACTER_REFERENCE = 78
      LEX_NUMERIC_CHARACTER_REFERENCE_END = 79

      # GumboTokenType
      TOKEN_DOCTYPE = 0
      TOKEN_START_TAG = 1
      TOKEN_END_TAG = 2
      TOKEN_COMMENT = 3
      TOKEN_WHITESPACE = 4
      TOKEN_CHARACTER = 5
      TOKEN_CDATA = 6
      TOKEN_NULL = 7
      TOKEN_EOF = 8

      # GumboInsertionMode
      INSERTION_MODE_INITIAL = 0
      INSERTION_MODE_BEFORE_HTML = 1
      INSERTION_MODE_BEFORE_HEAD = 2
      INSERTION_MODE_IN_HEAD = 3
      INSERTION_MODE_IN_HEAD_NOSCRIPT = 4
      INSERTION_MODE_AFTER_HEAD = 5
      INSERTION_MODE_IN_BODY = 6
      INSERTION_MODE_TEXT = 7
      INSERTION_MODE_IN_TABLE = 8
      INSERTION_MODE_IN_TABLE_TEXT = 9
      INSERTION_MODE_IN_CAPTION = 10
      INSERTION_MODE_IN_COLUMN_GROUP = 11
      INSERTION_MODE_IN_TABLE_BODY = 12
      INSERTION_MODE_IN_ROW = 13
      INSERTION_MODE_IN_CELL = 14
      INSERTION_MODE_IN_SELECT = 15
      INSERTION_MODE_IN_SELECT_IN_TABLE = 16
      INSERTION_MODE_IN_TEMPLATE = 17
      INSERTION_MODE_AFTER_BODY = 18
      INSERTION_MODE_IN_FRAMESET = 19
      INSERTION_MODE_AFTER_FRAMESET = 20
      INSERTION_MODE_AFTER_AFTER_BODY = 21
      INSERTION_MODE_AFTER_AFTER_FRAMESET = 22

      # GumboErrorType
      ERR_ABRUPT_CLOSING_OF_EMPTY_COMMENT = 0
      ERR_ABRUPT_DOCTYPE_PUBLIC_IDENTIFIER = 1
      ERR_ABRUPT_DOCTYPE_SYSTEM_IDENTIFIER = 2
      ERR_ABSENCE_OF_DIGITS_IN_NUMERIC_CHARACTER_REFERENCE = 3
      ERR_CDATA_IN_HTML_CONTENT = 4
      ERR_CHARACTER_REFERENCE_OUTSIDE_UNICODE_RANGE = 5
      ERR_CONTROL_CHARACTER_IN_INPUT_STREAM = 6
      ERR_CONTROL_CHARACTER_REFERENCE = 7
      ERR_END_TAG_WITH_ATTRIBUTES = 8
      ERR_DUPLICATE_ATTRIBUTE = 9
      ERR_END_TAG_WITH_TRAILING_SOLIDUS = 10
      ERR_EOF_BEFORE_TAG_NAME = 11
      ERR_EOF_IN_CDATA = 12
      ERR_EOF_IN_COMMENT = 13
      ERR_EOF_IN_DOCTYPE = 14
      ERR_EOF_IN_SCRIPT_HTML_COMMENT_LIKE_TEXT = 15
      ERR_EOF_IN_TAG = 16
      ERR_INCORRECTLY_CLOSED_COMMENT = 17
      ERR_INCORRECTLY_OPENED_COMMENT = 18
      ERR_INVALID_CHARACTER_SEQUENCE_AFTER_DOCTYPE_NAME = 19
      ERR_INVALID_FIRST_CHARACTER_OF_TAG_NAME = 20
      ERR_MISSING_ATTRIBUTE_VALUE = 21
      ERR_MISSING_DOCTYPE_NAME = 22
      ERR_MISSING_DOCTYPE_PUBLIC_IDENTIFIER = 23
      ERR_MISSING_DOCTYPE_SYSTEM_IDENTIFIER = 24
      ERR_MISSING_END_TAG_NAME = 25
      ERR_MISSING_QUOTE_BEFORE_DOCTYPE_PUBLIC_IDENTIFIER = 26
      ERR_MISSING_QUOTE_BEFORE_DOCTYPE_SYSTEM_IDENTIFIER = 27
      ERR_MISSING_SEMICOLON_AFTER_CHARACTER_REFERENCE = 28
      ERR_MISSING_WHITESPACE_AFTER_DOCTYPE_PUBLIC_KEYWORD = 29
      ERR_MISSING_WHITESPACE_AFTER_DOCTYPE_SYSTEM_KEYWORD = 30
      ERR_MISSING_WHITESPACE_BEFORE_DOCTYPE_NAME = 31
      ERR_MISSING_WHITESPACE_BETWEEN_ATTRIBUTES = 32
      ERR_MISSING_WHITESPACE_BETWEEN_DOCTYPE_PUBLIC_AND_SYSTEM_IDENTIFIERS = 33
      ERR_NESTED_COMMENT = 34
      ERR_NONCHARACTER_CHARACTER_REFERENCE = 35
      ERR_NONCHARACTER_IN_INPUT_STREAM = 36
      ERR_NON_VOID_HTML_ELEMENT_START_TAG_WITH_TRAILING_SOLIDUS = 37
      ERR_NULL_CHARACTER_REFERENCE = 38
      ERR_SURROGATE_CHARACTER_REFERENCE = 39
      ERR_SURROGATE_IN_INPUT_STREAM = 40
      ERR_UNEXPECTED_CHARACTER_AFTER_DOCTYPE_SYSTEM_IDENTIFIER = 41
      ERR_UNEXPECTED_CHARACTER_IN_ATTRIBUTE_NAME = 42
      ERR_UNEXPECTED_CHARACTER_IN_UNQUOTED_ATTRIBUTE_VALUE = 43
      ERR_UNEXPECTED_EQUALS_SIGN_BEFORE_ATTRIBUTE_NAME = 44
      ERR_UNEXPECTED_NULL_CHARACTER = 45
      ERR_UNEXPECTED_QUESTION_MARK_INSTEAD_OF_TAG_NAME = 46
      ERR_UNEXPECTED_SOLIDUS_IN_TAG = 47
      ERR_UNKNOWN_NAMED_CHARACTER_REFERENCE = 48
      ERR_UTF8_INVALID = 49
      ERR_UTF8_TRUNCATED = 50
      ERR_PARSER = 51

      # GumboNodeType
      NODE_DOCUMENT = 0
      NODE_ELEMENT = 1
      NODE_TEXT = 2
      NODE_CDATA = 3
      NODE_COMMENT = 4
      NODE_WHITESPACE = 5
      NODE_TEMPLATE = 6

      # GumboNamespaceEnum
      NAMESPACE_HTML = 0
      NAMESPACE_SVG = 1
      NAMESPACE_MATHML = 2

      # GumboAttributeNamespaceEnum
      ATTR_NAMESPACE_NONE = 0
      ATTR_NAMESPACE_XLINK = 1
      ATTR_NAMESPACE_XML = 2
      ATTR_NAMESPACE_XMLNS = 3

      # GumboQuirksModeEnum
      DOCTYPE_NO_QUIRKS = 0
      DOCTYPE_QUIRKS = 1
      DOCTYPE_LIMITED_QUIRKS = 2

      # GumboOutputStatus
      STATUS_OK = 0
      STATUS_TREE_TOO_DEEP = 1
      STATUS_TOO_MANY_ATTRIBUTES = 2
      STATUS_OUT_OF_MEMORY = 3

      NO_CHAR = -1 # kGumboNoChar
      REPLACEMENT_CHAR = 0xFFFD
      BOM_CHAR = 0xFEFF
      MAX_CHAR = 0x10FFFF

      UINT_MAX = 0xFFFFFFFF
    end
  end
end
