# frozen_string_literal: true

# Generated by test-pure/html5/gen_tables.rb from gumbo-parser (tag.c, *.gperf). Do not edit.

module Nokogiri
  module Pure
    module Gumbo
      TAG_HTML = 0
      TAG_HEAD = 1
      TAG_TITLE = 2
      TAG_BASE = 3
      TAG_LINK = 4
      TAG_META = 5
      TAG_STYLE = 6
      TAG_SCRIPT = 7
      TAG_NOSCRIPT = 8
      TAG_TEMPLATE = 9
      TAG_BODY = 10
      TAG_ARTICLE = 11
      TAG_SECTION = 12
      TAG_NAV = 13
      TAG_ASIDE = 14
      TAG_H1 = 15
      TAG_H2 = 16
      TAG_H3 = 17
      TAG_H4 = 18
      TAG_H5 = 19
      TAG_H6 = 20
      TAG_HGROUP = 21
      TAG_HEADER = 22
      TAG_FOOTER = 23
      TAG_ADDRESS = 24
      TAG_P = 25
      TAG_HR = 26
      TAG_PRE = 27
      TAG_BLOCKQUOTE = 28
      TAG_OL = 29
      TAG_UL = 30
      TAG_LI = 31
      TAG_DL = 32
      TAG_DT = 33
      TAG_DD = 34
      TAG_FIGURE = 35
      TAG_FIGCAPTION = 36
      TAG_MAIN = 37
      TAG_DIV = 38
      TAG_A = 39
      TAG_EM = 40
      TAG_STRONG = 41
      TAG_SMALL = 42
      TAG_S = 43
      TAG_CITE = 44
      TAG_Q = 45
      TAG_DFN = 46
      TAG_ABBR = 47
      TAG_DATA = 48
      TAG_TIME = 49
      TAG_CODE = 50
      TAG_VAR = 51
      TAG_SAMP = 52
      TAG_KBD = 53
      TAG_SUB = 54
      TAG_SUP = 55
      TAG_I = 56
      TAG_B = 57
      TAG_U = 58
      TAG_MARK = 59
      TAG_RUBY = 60
      TAG_RT = 61
      TAG_RP = 62
      TAG_BDI = 63
      TAG_BDO = 64
      TAG_SPAN = 65
      TAG_BR = 66
      TAG_WBR = 67
      TAG_INS = 68
      TAG_DEL = 69
      TAG_IMAGE = 70
      TAG_IMG = 71
      TAG_IFRAME = 72
      TAG_EMBED = 73
      TAG_OBJECT = 74
      TAG_PARAM = 75
      TAG_VIDEO = 76
      TAG_AUDIO = 77
      TAG_SOURCE = 78
      TAG_TRACK = 79
      TAG_CANVAS = 80
      TAG_MAP = 81
      TAG_AREA = 82
      TAG_MATH = 83
      TAG_MI = 84
      TAG_MO = 85
      TAG_MN = 86
      TAG_MS = 87
      TAG_MTEXT = 88
      TAG_MGLYPH = 89
      TAG_MALIGNMARK = 90
      TAG_ANNOTATION_XML = 91
      TAG_SVG = 92
      TAG_FOREIGNOBJECT = 93
      TAG_DESC = 94
      TAG_TABLE = 95
      TAG_CAPTION = 96
      TAG_COLGROUP = 97
      TAG_COL = 98
      TAG_TBODY = 99
      TAG_THEAD = 100
      TAG_TFOOT = 101
      TAG_TR = 102
      TAG_TD = 103
      TAG_TH = 104
      TAG_FORM = 105
      TAG_FIELDSET = 106
      TAG_LEGEND = 107
      TAG_LABEL = 108
      TAG_INPUT = 109
      TAG_BUTTON = 110
      TAG_SELECT = 111
      TAG_DATALIST = 112
      TAG_OPTGROUP = 113
      TAG_OPTION = 114
      TAG_TEXTAREA = 115
      TAG_KEYGEN = 116
      TAG_OUTPUT = 117
      TAG_PROGRESS = 118
      TAG_METER = 119
      TAG_DETAILS = 120
      TAG_SUMMARY = 121
      TAG_MENU = 122
      TAG_MENUITEM = 123
      TAG_APPLET = 124
      TAG_ACRONYM = 125
      TAG_BGSOUND = 126
      TAG_DIR = 127
      TAG_FRAME = 128
      TAG_FRAMESET = 129
      TAG_NOFRAMES = 130
      TAG_LISTING = 131
      TAG_XMP = 132
      TAG_NEXTID = 133
      TAG_NOEMBED = 134
      TAG_PLAINTEXT = 135
      TAG_RB = 136
      TAG_STRIKE = 137
      TAG_BASEFONT = 138
      TAG_BIG = 139
      TAG_BLINK = 140
      TAG_CENTER = 141
      TAG_FONT = 142
      TAG_MARQUEE = 143
      TAG_MULTICOL = 144
      TAG_NOBR = 145
      TAG_SPACER = 146
      TAG_TT = 147
      TAG_RTC = 148
      TAG_DIALOG = 149
      TAG_SEARCH = 150
      TAG_UNKNOWN = 151
      TAG_LAST = 152

      # kGumboTagNames
      TAG_NAMES = [
        "html".b.freeze,
        "head".b.freeze,
        "title".b.freeze,
        "base".b.freeze,
        "link".b.freeze,
        "meta".b.freeze,
        "style".b.freeze,
        "script".b.freeze,
        "noscript".b.freeze,
        "template".b.freeze,
        "body".b.freeze,
        "article".b.freeze,
        "section".b.freeze,
        "nav".b.freeze,
        "aside".b.freeze,
        "h1".b.freeze,
        "h2".b.freeze,
        "h3".b.freeze,
        "h4".b.freeze,
        "h5".b.freeze,
        "h6".b.freeze,
        "hgroup".b.freeze,
        "header".b.freeze,
        "footer".b.freeze,
        "address".b.freeze,
        "p".b.freeze,
        "hr".b.freeze,
        "pre".b.freeze,
        "blockquote".b.freeze,
        "ol".b.freeze,
        "ul".b.freeze,
        "li".b.freeze,
        "dl".b.freeze,
        "dt".b.freeze,
        "dd".b.freeze,
        "figure".b.freeze,
        "figcaption".b.freeze,
        "main".b.freeze,
        "div".b.freeze,
        "a".b.freeze,
        "em".b.freeze,
        "strong".b.freeze,
        "small".b.freeze,
        "s".b.freeze,
        "cite".b.freeze,
        "q".b.freeze,
        "dfn".b.freeze,
        "abbr".b.freeze,
        "data".b.freeze,
        "time".b.freeze,
        "code".b.freeze,
        "var".b.freeze,
        "samp".b.freeze,
        "kbd".b.freeze,
        "sub".b.freeze,
        "sup".b.freeze,
        "i".b.freeze,
        "b".b.freeze,
        "u".b.freeze,
        "mark".b.freeze,
        "ruby".b.freeze,
        "rt".b.freeze,
        "rp".b.freeze,
        "bdi".b.freeze,
        "bdo".b.freeze,
        "span".b.freeze,
        "br".b.freeze,
        "wbr".b.freeze,
        "ins".b.freeze,
        "del".b.freeze,
        "image".b.freeze,
        "img".b.freeze,
        "iframe".b.freeze,
        "embed".b.freeze,
        "object".b.freeze,
        "param".b.freeze,
        "video".b.freeze,
        "audio".b.freeze,
        "source".b.freeze,
        "track".b.freeze,
        "canvas".b.freeze,
        "map".b.freeze,
        "area".b.freeze,
        "math".b.freeze,
        "mi".b.freeze,
        "mo".b.freeze,
        "mn".b.freeze,
        "ms".b.freeze,
        "mtext".b.freeze,
        "mglyph".b.freeze,
        "malignmark".b.freeze,
        "annotation-xml".b.freeze,
        "svg".b.freeze,
        "foreignobject".b.freeze,
        "desc".b.freeze,
        "table".b.freeze,
        "caption".b.freeze,
        "colgroup".b.freeze,
        "col".b.freeze,
        "tbody".b.freeze,
        "thead".b.freeze,
        "tfoot".b.freeze,
        "tr".b.freeze,
        "td".b.freeze,
        "th".b.freeze,
        "form".b.freeze,
        "fieldset".b.freeze,
        "legend".b.freeze,
        "label".b.freeze,
        "input".b.freeze,
        "button".b.freeze,
        "select".b.freeze,
        "datalist".b.freeze,
        "optgroup".b.freeze,
        "option".b.freeze,
        "textarea".b.freeze,
        "keygen".b.freeze,
        "output".b.freeze,
        "progress".b.freeze,
        "meter".b.freeze,
        "details".b.freeze,
        "summary".b.freeze,
        "menu".b.freeze,
        "menuitem".b.freeze,
        "applet".b.freeze,
        "acronym".b.freeze,
        "bgsound".b.freeze,
        "dir".b.freeze,
        "frame".b.freeze,
        "frameset".b.freeze,
        "noframes".b.freeze,
        "listing".b.freeze,
        "xmp".b.freeze,
        "nextid".b.freeze,
        "noembed".b.freeze,
        "plaintext".b.freeze,
        "rb".b.freeze,
        "strike".b.freeze,
        "basefont".b.freeze,
        "big".b.freeze,
        "blink".b.freeze,
        "center".b.freeze,
        "font".b.freeze,
        "marquee".b.freeze,
        "multicol".b.freeze,
        "nobr".b.freeze,
        "spacer".b.freeze,
        "tt".b.freeze,
        "rtc".b.freeze,
        "dialog".b.freeze,
        "search".b.freeze,
        "".b.freeze,
        "".b.freeze,
      ].freeze

      # gumbo_get_svg_tag_replacement (keys are lower case; lookup is ASCII case-insensitive)
      SVG_TAG_REPLACEMENTS = {
        "altglyph".b => "altGlyph".b.freeze,
        "altglyphdef".b => "altGlyphDef".b.freeze,
        "altglyphitem".b => "altGlyphItem".b.freeze,
        "animatecolor".b => "animateColor".b.freeze,
        "animatemotion".b => "animateMotion".b.freeze,
        "animatetransform".b => "animateTransform".b.freeze,
        "clippath".b => "clipPath".b.freeze,
        "feblend".b => "feBlend".b.freeze,
        "fecolormatrix".b => "feColorMatrix".b.freeze,
        "fecomponenttransfer".b => "feComponentTransfer".b.freeze,
        "fecomposite".b => "feComposite".b.freeze,
        "feconvolvematrix".b => "feConvolveMatrix".b.freeze,
        "fediffuselighting".b => "feDiffuseLighting".b.freeze,
        "fedisplacementmap".b => "feDisplacementMap".b.freeze,
        "fedistantlight".b => "feDistantLight".b.freeze,
        "feflood".b => "feFlood".b.freeze,
        "fefunca".b => "feFuncA".b.freeze,
        "fefuncb".b => "feFuncB".b.freeze,
        "fefuncg".b => "feFuncG".b.freeze,
        "fefuncr".b => "feFuncR".b.freeze,
        "fegaussianblur".b => "feGaussianBlur".b.freeze,
        "feimage".b => "feImage".b.freeze,
        "femerge".b => "feMerge".b.freeze,
        "femergenode".b => "feMergeNode".b.freeze,
        "femorphology".b => "feMorphology".b.freeze,
        "feoffset".b => "feOffset".b.freeze,
        "fepointlight".b => "fePointLight".b.freeze,
        "fespecularlighting".b => "feSpecularLighting".b.freeze,
        "fespotlight".b => "feSpotLight".b.freeze,
        "fetile".b => "feTile".b.freeze,
        "feturbulence".b => "feTurbulence".b.freeze,
        "foreignobject".b => "foreignObject".b.freeze,
        "glyphref".b => "glyphRef".b.freeze,
        "lineargradient".b => "linearGradient".b.freeze,
        "radialgradient".b => "radialGradient".b.freeze,
        "textpath".b => "textPath".b.freeze,
      }.freeze

      # gumbo_get_svg_attr_replacement (keys are lower case; lookup is ASCII case-insensitive)
      SVG_ATTR_REPLACEMENTS = {
        "attributename".b => "attributeName".b.freeze,
        "attributetype".b => "attributeType".b.freeze,
        "basefrequency".b => "baseFrequency".b.freeze,
        "baseprofile".b => "baseProfile".b.freeze,
        "calcmode".b => "calcMode".b.freeze,
        "clippathunits".b => "clipPathUnits".b.freeze,
        "diffuseconstant".b => "diffuseConstant".b.freeze,
        "edgemode".b => "edgeMode".b.freeze,
        "filterunits".b => "filterUnits".b.freeze,
        "glyphref".b => "glyphRef".b.freeze,
        "gradienttransform".b => "gradientTransform".b.freeze,
        "gradientunits".b => "gradientUnits".b.freeze,
        "kernelmatrix".b => "kernelMatrix".b.freeze,
        "kernelunitlength".b => "kernelUnitLength".b.freeze,
        "keypoints".b => "keyPoints".b.freeze,
        "keysplines".b => "keySplines".b.freeze,
        "keytimes".b => "keyTimes".b.freeze,
        "lengthadjust".b => "lengthAdjust".b.freeze,
        "limitingconeangle".b => "limitingConeAngle".b.freeze,
        "markerheight".b => "markerHeight".b.freeze,
        "markerunits".b => "markerUnits".b.freeze,
        "markerwidth".b => "markerWidth".b.freeze,
        "maskcontentunits".b => "maskContentUnits".b.freeze,
        "maskunits".b => "maskUnits".b.freeze,
        "numoctaves".b => "numOctaves".b.freeze,
        "pathlength".b => "pathLength".b.freeze,
        "patterncontentunits".b => "patternContentUnits".b.freeze,
        "patterntransform".b => "patternTransform".b.freeze,
        "patternunits".b => "patternUnits".b.freeze,
        "pointsatx".b => "pointsAtX".b.freeze,
        "pointsaty".b => "pointsAtY".b.freeze,
        "pointsatz".b => "pointsAtZ".b.freeze,
        "preservealpha".b => "preserveAlpha".b.freeze,
        "preserveaspectratio".b => "preserveAspectRatio".b.freeze,
        "primitiveunits".b => "primitiveUnits".b.freeze,
        "refx".b => "refX".b.freeze,
        "refy".b => "refY".b.freeze,
        "repeatcount".b => "repeatCount".b.freeze,
        "repeatdur".b => "repeatDur".b.freeze,
        "requiredextensions".b => "requiredExtensions".b.freeze,
        "requiredfeatures".b => "requiredFeatures".b.freeze,
        "specularconstant".b => "specularConstant".b.freeze,
        "specularexponent".b => "specularExponent".b.freeze,
        "spreadmethod".b => "spreadMethod".b.freeze,
        "startoffset".b => "startOffset".b.freeze,
        "stddeviation".b => "stdDeviation".b.freeze,
        "stitchtiles".b => "stitchTiles".b.freeze,
        "surfacescale".b => "surfaceScale".b.freeze,
        "systemlanguage".b => "systemLanguage".b.freeze,
        "tablevalues".b => "tableValues".b.freeze,
        "targetx".b => "targetX".b.freeze,
        "targety".b => "targetY".b.freeze,
        "textlength".b => "textLength".b.freeze,
        "viewbox".b => "viewBox".b.freeze,
        "viewtarget".b => "viewTarget".b.freeze,
        "xchannelselector".b => "xChannelSelector".b.freeze,
        "ychannelselector".b => "yChannelSelector".b.freeze,
        "zoomandpan".b => "zoomAndPan".b.freeze,
      }.freeze

      # gumbo_get_foreign_attr_replacement (case-sensitive)
      FOREIGN_ATTR_REPLACEMENTS = {
        "xlink:actuate".b => ["actuate".b.freeze, ATTR_NAMESPACE_XLINK].freeze,
        "xlink:arcrole".b => ["arcrole".b.freeze, ATTR_NAMESPACE_XLINK].freeze,
        "xlink:href".b => ["href".b.freeze, ATTR_NAMESPACE_XLINK].freeze,
        "xlink:role".b => ["role".b.freeze, ATTR_NAMESPACE_XLINK].freeze,
        "xlink:show".b => ["show".b.freeze, ATTR_NAMESPACE_XLINK].freeze,
        "xlink:title".b => ["title".b.freeze, ATTR_NAMESPACE_XLINK].freeze,
        "xlink:type".b => ["type".b.freeze, ATTR_NAMESPACE_XLINK].freeze,
        "xml:lang".b => ["lang".b.freeze, ATTR_NAMESPACE_XML].freeze,
        "xml:space".b => ["space".b.freeze, ATTR_NAMESPACE_XML].freeze,
        "xmlns".b => ["xmlns".b.freeze, ATTR_NAMESPACE_XMLNS].freeze,
        "xmlns:xlink".b => ["xlink".b.freeze, ATTR_NAMESPACE_XMLNS].freeze,
      }.freeze
    end
  end
end
