# Generates lib/nokogiri/pure/gumbo/tables.rb and char_ref_table.rb from the gumbo C sources.
src = "/root/workspace/nokogiri-upstream/gumbo-parser/src"
out = File.expand_path("../../lib/nokogiri/pure/gumbo", __dir__)

h = File.read("#{src}/nokogiri_gumbo.h")
enum = h[/typedef enum \{\s*GUMBO_TAG_HTML.*?\} GumboTag;/m]
tags = enum.scan(/^\s*GUMBO_TAG_(\w+),/).flatten
tagc = File.read("#{src}/tag.c")
names = {}
tagc.scan(/\[GUMBO_TAG_(\w+)\] = "([^"]*)"/) { |t, n| names[t] = n }

def gperf_pairs(file)
  File.read(file).split("%%")[1].lines.map(&:strip).reject(&:empty?)
end

svg_tags = gperf_pairs("#{src}/svg_tags.gperf").map { |l| l.scan(/"([^"]*)"/).flatten }
svg_attrs = gperf_pairs("#{src}/svg_attrs.gperf").map { |l| l.scan(/"([^"]*)"/).flatten }
foreign = gperf_pairs("#{src}/foreign_attrs.gperf").map do |l|
  a, b, ns = l.split(",").map(&:strip)
  [a.delete('"'), b.delete('"'), ns.sub("GUMBO_", "")]
end

File.open("#{out}/tables.rb", "w") do |f|
  f.puts "# frozen_string_literal: true"
  f.puts
  f.puts "# Generated by test-pure/html5/gen_tables.rb from gumbo-parser (tag.c, *.gperf). Do not edit."
  f.puts
  f.puts "module Nokogiri"
  f.puts "  module Pure"
  f.puts "    module Gumbo"
  tags.each_with_index { |t, i| f.puts "      TAG_#{t} = #{i}" }
  f.puts
  f.puts "      # kGumboTagNames"
  f.puts "      TAG_NAMES = ["
  tags.each { |t| f.puts "        #{(names[t] || "").inspect}.b.freeze," }
  f.puts "      ].freeze"
  f.puts
  f.puts "      # gumbo_get_svg_tag_replacement (keys are lower case; lookup is ASCII case-insensitive)"
  f.puts "      SVG_TAG_REPLACEMENTS = {"
  svg_tags.each { |a, b| f.puts "        #{a.inspect}.b => #{b.inspect}.b.freeze," }
  f.puts "      }.freeze"
  f.puts
  f.puts "      # gumbo_get_svg_attr_replacement (keys are lower case; lookup is ASCII case-insensitive)"
  f.puts "      SVG_ATTR_REPLACEMENTS = {"
  svg_attrs.each { |a, b| f.puts "        #{a.inspect}.b => #{b.inspect}.b.freeze," }
  f.puts "      }.freeze"
  f.puts
  f.puts "      # gumbo_get_foreign_attr_replacement (case-sensitive)"
  f.puts "      FOREIGN_ATTR_REPLACEMENTS = {"
  foreign.each { |a, b, ns| f.puts "        #{a.inspect}.b => [#{b.inspect}.b.freeze, #{ns}].freeze," }
  f.puts "      }.freeze"
  f.puts "    end"
  f.puts "  end"
  f.puts "end"
end

ents = []
File.read("#{src}/char_ref.rl").scan(/^  '([^']*)'( \. ';'\?)? => \{output\[0\]=0x(\h+);(?: output\[1\]=0x(\h+);)?/) do |name, opt, a, b|
  ents << [name, !opt.nil?, a.to_i(16), b&.to_i(16)]
end
File.open("#{out}/char_ref_table.rb", "w") do |f|
  f.puts "# frozen_string_literal: true"
  f.puts
  f.puts "# Generated by test-pure/html5/gen_tables.rb from gumbo-parser/src/char_ref.rl. Do not edit."
  f.puts "# name => code point, or [code point, code point]."
  f.puts
  f.puts "module Nokogiri"
  f.puts "  module Pure"
  f.puts "    module Gumbo"
  f.puts "      NAMED_CHAR_REFS = {"
  ents.each do |name, opt, a, b|
    v = b ? "[0x#{a.to_s(16)}, 0x#{b.to_s(16)}].freeze" : "0x#{a.to_s(16)}"
    keys = opt ? [name, name + ";"] : [name]
    keys.each { |k| f.puts "        #{k.inspect}.b => #{v}," }
  end
  f.puts "      }.freeze"
  f.puts "    end"
  f.puts "  end"
  f.puts "end"
end
puts "tags=#{tags.size} svg_tags=#{svg_tags.size} svg_attrs=#{svg_attrs.size} foreign=#{foreign.size} ents=#{ents.size}"
