# frozen_string_literal: true

# Minitest wrapper around the cached differential fixtures (fixtures/*.json.gz, produced by
# run_diff.rb with the native libxml2 oracle). Does not need the native gem.
#   ruby test-pure/schema/regexp/test_regexp_diff.rb            # fast suites
#   REGEXP_DIFF_ALL=1 ruby test-pure/schema/regexp/test_regexp_diff.rb   # + fuzz_regexp (~2 min)
require "minitest/autorun"
require_relative "run_diff"

class TestXmlRegexpDifferential < Minitest::Test
  SLOW_SUITES = %w[fuzz_regexp].freeze

  RegexpCorpus::SUITES.each do |suite|
    define_method("test_#{suite}") do
      skip "set REGEXP_DIFF_ALL=1" if SLOW_SUITES.include?(suite) && !ENV["REGEXP_DIFF_ALL"]
      path = File.join(FIXTURES, "#{suite}.json.gz")
      skip "no fixture #{path} (run run_diff.rb with the native gem)" unless File.exist?(path)
      # the fixture's own cases are replayed (they are regenerated by run_diff.rb when
      # corpus.rb changes)
      data = JSON.parse(Zlib::GzipReader.open(path, &:read))
      _, fails, = compare_data(data)
      msgs = fails.first(5).map { |k, e, a| "#{JSON.generate(k)[0, 300]}\n  #{first_diff(e, a)}" }
      assert_empty fails, msgs.join("\n")
    end
  end
end
