# frozen_string_literal: true

# Static tables from libxml2 2.13.9 HTMLparser.c (html40ElementTable, htmlStartClose,
# html40EntitiesTable, ...) and the lookup functions over them (htmlTagLookup,
# htmlEntityLookup, htmlEntityValueLookup, htmlCheckAutoClose, ...).
#
# The element/entity tables were generated mechanically from the C source (compiled and dumped),
# so they match libxml2 exactly. Quirks preserved on purpose:
#  - fieldset's subelts array has no NULL terminator in C, so iterating it runs into the next
#    static array ("label"); the oracle returns [..., "legend", "label"].
#
# This file is self-contained (no parser dependencies) so the serializer can require it alone.

module Nokogiri
  module Pure
    module HTMLParser
      # htmlElemDesc. Flag fields are libxml2's ints (char), NOT booleans:
      #   start_tag:    1 = start tag can be omitted
      #   end_tag:      1 = end tag can be omitted, 2 = forbidden (empty), 3 = stylistic, close easily
      #   save_end_tag: 1 = don't save the end tag when serialising (sic: libxml2 semantics)
      #   empty, depr, isinline: 0/1; dtd: 0, 1 (loose only) or 2 (frameset only)
      ElemDesc = Struct.new(:name, :start_tag, :end_tag, :save_end_tag, :empty, :depr, :dtd, :isinline,
        :desc, :subelts, :defaultsubelt, :attrs_opt, :attrs_depr, :attrs_req) do
        alias_method :saveEndTag, :save_end_tag
        alias_method :startTag, :start_tag
        alias_method :endTag, :end_tag

        def inspect
          "#<Pure::HTMLParser::ElemDesc #{name}>"
        end
      end

      # htmlEntityDesc
      EntityDesc = Struct.new(:value, :name, :desc)

      ELEMENT_TABLE = [
        ElemDesc.new("a", 0, 0, 0, 0, 0, 0, 1, "anchor ",
          ["tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup", "charset", "type", "name", "href", "hreflang", "rel", "rev", "accesskey", "shape", "coords", "tabindex", "onfocus", "onblur"].freeze,
          ["target"].freeze,
          nil),
        ElemDesc.new("abbr", 0, 0, 0, 0, 0, 0, 1, "abbreviated form",
          ["tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          nil,
          nil),
        ElemDesc.new("acronym", 0, 0, 0, 0, 0, 0, 1, "",
          ["tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          nil,
          nil),
        ElemDesc.new("address", 0, 0, 0, 0, 0, 0, 0, "information on author ",
          ["tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button", "p"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          nil,
          nil),
        ElemDesc.new("applet", 0, 0, 0, 0, 1, 1, 2, "java applet ",
          ["h1", "h2", "h3", "h4", "h5", "h6", "ul", "ol", "dir", "menu", "pre", "p", "dl", "div", "center", "noscript", "noframes", "blockquote", "form", "isindex", "hr", "table", "fieldset", "address", "tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button", "param"].freeze, nil,
          nil,
          ["id", "class", "style", "title", "codebase", "archive", "alt", "name", "height", "width", "align", "hspace", "vspace"].freeze,
          nil),
        ElemDesc.new("area", 0, 2, 2, 1, 0, 0, 0, "client-side image map area ",
          nil, nil,
          ["shape", "coords", "href", "nohref", "tabindex", "accesskey", "onfocus", "onblur"].freeze,
          ["target"].freeze,
          ["alt"].freeze),
        ElemDesc.new("b", 0, 3, 0, 0, 0, 0, 1, "bold text style",
          ["tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          nil,
          nil),
        ElemDesc.new("base", 0, 2, 2, 1, 0, 0, 0, "document base uri ",
          nil, nil,
          nil,
          ["target"].freeze,
          ["href"].freeze),
        ElemDesc.new("basefont", 0, 2, 2, 1, 1, 1, 1, "base font size ",
          nil, nil,
          nil,
          ["id", "size", "color", "face"].freeze,
          nil),
        ElemDesc.new("bdo", 0, 0, 0, 0, 0, 0, 1, "i18n bidi over-ride ",
          ["tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir"].freeze,
          nil,
          ["dir"].freeze),
        ElemDesc.new("big", 0, 3, 0, 0, 0, 0, 1, "large text style",
          ["tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          nil,
          nil),
        ElemDesc.new("blockquote", 0, 0, 0, 0, 0, 0, 0, "long quotation ",
          ["h1", "h2", "h3", "h4", "h5", "h6", "ul", "ol", "dir", "menu", "pre", "p", "dl", "div", "center", "noscript", "noframes", "blockquote", "form", "isindex", "hr", "table", "fieldset", "address", "tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup", "cite"].freeze,
          nil,
          nil),
        ElemDesc.new("body", 1, 1, 0, 0, 0, 0, 0, "document body ",
          ["h1", "h2", "h3", "h4", "h5", "h6", "ul", "ol", "dir", "menu", "pre", "p", "dl", "div", "center", "noscript", "noframes", "blockquote", "form", "isindex", "hr", "table", "fieldset", "address", "tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button", "ins", "del"].freeze, "div",
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup", "onload", "onunload"].freeze,
          ["background", "bgcolor", "text", "link", "vlink", "alink"].freeze,
          nil),
        ElemDesc.new("br", 0, 2, 2, 1, 0, 0, 1, "forced line break ",
          nil, nil,
          ["id", "class", "style", "title"].freeze,
          ["clear"].freeze,
          nil),
        ElemDesc.new("button", 0, 0, 0, 0, 0, 0, 2, "push button ",
          ["h1", "h2", "h3", "h4", "h5", "h6", "ul", "ol", "dir", "menu", "pre", "p", "dl", "div", "center", "noscript", "noframes", "blockquote", "form", "isindex", "hr", "table", "fieldset", "address", "tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup", "name", "value", "type", "disabled", "tabindex", "accesskey", "onfocus", "onblur"].freeze,
          nil,
          nil),
        ElemDesc.new("caption", 0, 0, 0, 0, 0, 0, 0, "table caption ",
          ["tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          nil,
          nil),
        ElemDesc.new("center", 0, 3, 0, 0, 1, 1, 0, "shorthand for div align=center ",
          ["h1", "h2", "h3", "h4", "h5", "h6", "ul", "ol", "dir", "menu", "pre", "p", "dl", "div", "center", "noscript", "noframes", "blockquote", "form", "isindex", "hr", "table", "fieldset", "address", "tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          nil),
        ElemDesc.new("cite", 0, 0, 0, 0, 0, 0, 1, "citation",
          ["tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          nil,
          nil),
        ElemDesc.new("code", 0, 0, 0, 0, 0, 0, 1, "computer code fragment",
          ["tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          nil,
          nil),
        ElemDesc.new("col", 0, 2, 2, 1, 0, 0, 0, "table column ",
          nil, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup", "span", "width", "align", "char", "charoff", "valign"].freeze,
          nil,
          nil),
        ElemDesc.new("colgroup", 0, 1, 0, 0, 0, 0, 0, "table column group ",
          ["col"].freeze, "col",
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup", "span", "width", "align", "char", "charoff", "valign"].freeze,
          nil,
          nil),
        ElemDesc.new("dd", 0, 1, 0, 0, 0, 0, 0, "definition description ",
          ["h1", "h2", "h3", "h4", "h5", "h6", "ul", "ol", "dir", "menu", "pre", "p", "dl", "div", "center", "noscript", "noframes", "blockquote", "form", "isindex", "hr", "table", "fieldset", "address", "tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          nil,
          nil),
        ElemDesc.new("del", 0, 0, 0, 0, 0, 0, 2, "deleted text ",
          ["h1", "h2", "h3", "h4", "h5", "h6", "ul", "ol", "dir", "menu", "pre", "p", "dl", "div", "center", "noscript", "noframes", "blockquote", "form", "isindex", "hr", "table", "fieldset", "address", "tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup", "datetime", "cite"].freeze,
          nil,
          nil),
        ElemDesc.new("dfn", 0, 0, 0, 0, 0, 0, 1, "instance definition",
          ["tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          nil,
          nil),
        ElemDesc.new("dir", 0, 0, 0, 0, 1, 1, 0, "directory list",
          ["h1", "h2", "h3", "h4", "h5", "h6", "ul", "ol", "dir", "menu", "pre", "p", "dl", "div", "center", "noscript", "noframes", "blockquote", "form", "isindex", "hr", "table", "fieldset", "address", "li"].freeze, "li",
          nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup", "compact"].freeze,
          nil),
        ElemDesc.new("div", 0, 0, 0, 0, 0, 0, 0, "generic language/style container",
          ["h1", "h2", "h3", "h4", "h5", "h6", "ul", "ol", "dir", "menu", "pre", "p", "dl", "div", "center", "noscript", "noframes", "blockquote", "form", "isindex", "hr", "table", "fieldset", "address", "tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          ["align"].freeze,
          nil),
        ElemDesc.new("dl", 0, 0, 0, 0, 0, 0, 0, "definition list ",
          ["dt", "dd"].freeze, "dd",
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          ["compact"].freeze,
          nil),
        ElemDesc.new("dt", 0, 1, 0, 0, 0, 0, 0, "definition term ",
          ["tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          nil,
          nil),
        ElemDesc.new("em", 0, 3, 0, 0, 0, 0, 1, "emphasis",
          ["tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          nil,
          nil),
        ElemDesc.new("embed", 0, 1, 0, 0, 1, 1, 1, "generic embedded object ",
          nil, nil,
          ["id", "class", "style", "title", "align", "alt", "border", "code", "codebase", "frameborder", "height", "hidden", "hspace", "name", "palette", "pluginspace", "pluginurl", "src", "type", "units", "vspace", "width"].freeze,
          nil,
          nil),
        ElemDesc.new("fieldset", 0, 0, 0, 0, 0, 0, 0, "form control group ",
          ["h1", "h2", "h3", "h4", "h5", "h6", "ul", "ol", "dir", "menu", "pre", "p", "dl", "div", "center", "noscript", "noframes", "blockquote", "form", "isindex", "hr", "table", "fieldset", "address", "tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button", "legend", "label"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          nil,
          nil),
        ElemDesc.new("font", 0, 3, 0, 0, 1, 1, 1, "local change to font ",
          ["tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          nil,
          ["id", "class", "style", "title", "lang", "dir", "size", "color", "face"].freeze,
          nil),
        ElemDesc.new("form", 0, 0, 0, 0, 0, 0, 0, "interactive form ",
          ["h1", "h2", "h3", "h4", "h5", "h6", "ul", "ol", "dir", "menu", "tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button", "pre", "p", "div", "center", "noscript", "noframes", "blockquote", "isindex", "hr", "table", "fieldset", "address"].freeze, "fieldset",
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup", "method", "enctype", "accept", "name", "onsubmit", "onreset", "accept-charset"].freeze,
          ["target"].freeze,
          ["action"].freeze),
        ElemDesc.new("frame", 0, 2, 2, 1, 0, 2, 0, "subwindow ",
          nil, nil,
          nil,
          ["id", "class", "style", "title", "longdesc", "name", "src", "frameborder", "marginwidth", "marginheight", "noresize", "scrolling"].freeze,
          nil),
        ElemDesc.new("frameset", 0, 0, 0, 0, 0, 2, 0, "window subdivision",
          ["frameset", "frame", "noframes"].freeze, "noframes",
          nil,
          ["id", "class", "style", "title", "rows", "cols", "onload", "onunload"].freeze,
          nil),
        ElemDesc.new("h1", 0, 0, 0, 0, 0, 0, 0, "heading ",
          ["tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          ["align"].freeze,
          nil),
        ElemDesc.new("h2", 0, 0, 0, 0, 0, 0, 0, "heading ",
          ["tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          ["align"].freeze,
          nil),
        ElemDesc.new("h3", 0, 0, 0, 0, 0, 0, 0, "heading ",
          ["tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          ["align"].freeze,
          nil),
        ElemDesc.new("h4", 0, 0, 0, 0, 0, 0, 0, "heading ",
          ["tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          ["align"].freeze,
          nil),
        ElemDesc.new("h5", 0, 0, 0, 0, 0, 0, 0, "heading ",
          ["tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          ["align"].freeze,
          nil),
        ElemDesc.new("h6", 0, 0, 0, 0, 0, 0, 0, "heading ",
          ["tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          ["align"].freeze,
          nil),
        ElemDesc.new("head", 1, 1, 0, 0, 0, 0, 0, "document head ",
          ["title", "isindex", "base", "script", "style", "meta", "link", "object"].freeze, nil,
          ["lang", "dir", "profile"].freeze,
          nil,
          nil),
        ElemDesc.new("hr", 0, 2, 2, 1, 0, 0, 0, "horizontal rule ",
          nil, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          ["align", "noshade", "size", "width"].freeze,
          nil),
        ElemDesc.new("html", 1, 1, 0, 0, 0, 0, 0, "document root element ",
          ["head", "body", "frameset"].freeze, nil,
          ["lang", "dir"].freeze,
          ["version"].freeze,
          nil),
        ElemDesc.new("i", 0, 3, 0, 0, 0, 0, 1, "italic text style",
          ["tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          nil,
          nil),
        ElemDesc.new("iframe", 0, 0, 0, 0, 0, 1, 2, "inline subwindow ",
          ["h1", "h2", "h3", "h4", "h5", "h6", "ul", "ol", "dir", "menu", "pre", "p", "dl", "div", "center", "noscript", "noframes", "blockquote", "form", "isindex", "hr", "table", "fieldset", "address", "tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          nil,
          ["id", "class", "style", "title", "longdesc", "name", "src", "frameborder", "marginwidth", "marginheight", "scrolling", "align", "height", "width"].freeze,
          nil),
        ElemDesc.new("img", 0, 2, 2, 1, 0, 0, 1, "embedded image ",
          nil, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup", "longdesc", "name", "height", "width", "usemap", "ismap"].freeze,
          ["align"].freeze,
          ["src", "alt"].freeze),
        ElemDesc.new("input", 0, 2, 2, 1, 0, 0, 1, "form control ",
          nil, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup", "type", "name", "value", "checked", "disabled", "readonly", "size", "maxlength", "src", "alt", "usemap", "ismap", "tabindex", "accesskey", "onfocus", "onblur", "onselect", "onchange", "accept"].freeze,
          ["align"].freeze,
          nil),
        ElemDesc.new("ins", 0, 0, 0, 0, 0, 0, 2, "inserted text",
          ["h1", "h2", "h3", "h4", "h5", "h6", "ul", "ol", "dir", "menu", "pre", "p", "dl", "div", "center", "noscript", "noframes", "blockquote", "form", "isindex", "hr", "table", "fieldset", "address", "tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup", "datetime", "cite"].freeze,
          nil,
          nil),
        ElemDesc.new("isindex", 0, 2, 2, 1, 1, 1, 0, "single line prompt ",
          nil, nil,
          nil,
          ["id", "class", "style", "title", "lang", "dir", "prompt"].freeze,
          nil),
        ElemDesc.new("kbd", 0, 0, 0, 0, 0, 0, 1, "text to be entered by the user",
          ["tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          nil,
          nil),
        ElemDesc.new("label", 0, 0, 0, 0, 0, 0, 1, "form field label text ",
          ["tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup", "for", "accesskey", "onfocus", "onblur"].freeze,
          nil,
          nil),
        ElemDesc.new("legend", 0, 0, 0, 0, 0, 0, 0, "fieldset legend ",
          ["tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup", "accesskey"].freeze,
          ["align"].freeze,
          nil),
        ElemDesc.new("li", 0, 1, 1, 0, 0, 0, 0, "list item ",
          ["h1", "h2", "h3", "h4", "h5", "h6", "ul", "ol", "dir", "menu", "pre", "p", "dl", "div", "center", "noscript", "noframes", "blockquote", "form", "isindex", "hr", "table", "fieldset", "address", "tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          nil,
          nil),
        ElemDesc.new("link", 0, 2, 2, 1, 0, 0, 0, "a media-independent link ",
          nil, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup", "charset", "href", "hreflang", "type", "rel", "rev", "media"].freeze,
          ["target"].freeze,
          nil),
        ElemDesc.new("map", 0, 0, 0, 0, 0, 0, 2, "client-side image map ",
          ["h1", "h2", "h3", "h4", "h5", "h6", "ul", "ol", "dir", "menu", "pre", "p", "dl", "div", "center", "noscript", "noframes", "blockquote", "form", "isindex", "hr", "table", "fieldset", "address", "area"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          nil,
          ["name"].freeze),
        ElemDesc.new("menu", 0, 0, 0, 0, 1, 1, 0, "menu list ",
          ["h1", "h2", "h3", "h4", "h5", "h6", "ul", "ol", "dir", "menu", "pre", "p", "dl", "div", "center", "noscript", "noframes", "blockquote", "form", "isindex", "hr", "table", "fieldset", "address", "li"].freeze, nil,
          nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup", "compact"].freeze,
          nil),
        ElemDesc.new("meta", 0, 2, 2, 1, 0, 0, 0, "generic metainformation ",
          nil, nil,
          ["lang", "dir", "http-equiv", "name", "scheme", "charset"].freeze,
          nil,
          ["content"].freeze),
        ElemDesc.new("noframes", 0, 0, 0, 0, 0, 2, 0, "alternate content container for non frame-based rendering ",
          ["body", "h1", "h2", "h3", "h4", "h5", "h6", "ul", "ol", "dir", "menu", "pre", "p", "dl", "div", "center", "noscript", "noframes", "blockquote", "form", "isindex", "hr", "table", "fieldset", "address", "tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, "body",
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          nil,
          nil),
        ElemDesc.new("noscript", 0, 0, 0, 0, 0, 0, 0, "alternate content container for non script-based rendering ",
          ["h1", "h2", "h3", "h4", "h5", "h6", "ul", "ol", "dir", "menu", "pre", "p", "dl", "div", "center", "noscript", "noframes", "blockquote", "form", "isindex", "hr", "table", "fieldset", "address", "tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, "div",
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          nil,
          nil),
        ElemDesc.new("object", 0, 0, 0, 0, 0, 0, 2, "generic embedded object ",
          ["h1", "h2", "h3", "h4", "h5", "h6", "ul", "ol", "dir", "menu", "pre", "p", "dl", "div", "center", "noscript", "noframes", "blockquote", "form", "isindex", "hr", "table", "fieldset", "address", "tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button", "param"].freeze, "div",
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup", "declare", "classid", "codebase", "data", "type", "codetype", "archive", "standby", "height", "width", "usemap", "name", "tabindex"].freeze,
          ["align", "border", "hspace", "vspace"].freeze,
          nil),
        ElemDesc.new("ol", 0, 0, 0, 0, 0, 0, 0, "ordered list ",
          ["li"].freeze, "li",
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          ["type", "compact", "start"].freeze,
          nil),
        ElemDesc.new("optgroup", 0, 0, 0, 0, 0, 0, 0, "option group ",
          ["option"].freeze, "option",
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup", "disabled"].freeze,
          nil,
          ["label"].freeze),
        ElemDesc.new("option", 0, 1, 0, 0, 0, 0, 0, "selectable choice ",
          [].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup", "disabled", "label", "selected", "value"].freeze,
          nil,
          nil),
        ElemDesc.new("p", 0, 1, 0, 0, 0, 0, 0, "paragraph ",
          ["tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          ["align"].freeze,
          nil),
        ElemDesc.new("param", 0, 2, 2, 1, 0, 0, 0, "named property value ",
          nil, nil,
          ["id", "value", "valuetype", "type"].freeze,
          nil,
          ["name"].freeze),
        ElemDesc.new("pre", 0, 0, 0, 0, 0, 0, 0, "preformatted text ",
          ["em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "tt", "i", "b", "u", "s", "strike", "a", "br", "script", "map", "q", "span", "bdo", "iframe"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          ["width"].freeze,
          nil),
        ElemDesc.new("q", 0, 0, 0, 0, 0, 0, 1, "short inline quotation ",
          ["tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup", "cite"].freeze,
          nil,
          nil),
        ElemDesc.new("s", 0, 3, 0, 0, 1, 1, 1, "strike-through text style",
          ["tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          nil),
        ElemDesc.new("samp", 0, 0, 0, 0, 0, 0, 1, "sample program output, scripts, etc.",
          ["tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          nil,
          nil),
        ElemDesc.new("script", 0, 0, 0, 0, 0, 0, 2, "script statements ",
          [].freeze, nil,
          ["charset", "src", "defer", "event", "for"].freeze,
          ["language"].freeze,
          ["type"].freeze),
        ElemDesc.new("select", 0, 0, 0, 0, 0, 0, 1, "option selector ",
          ["optgroup", "option"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup", "name", "size", "multiple", "disabled", "tabindex", "onfocus", "onblur", "onchange"].freeze,
          nil,
          nil),
        ElemDesc.new("small", 0, 3, 0, 0, 0, 0, 1, "small text style",
          ["tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          nil,
          nil),
        ElemDesc.new("span", 0, 0, 0, 0, 0, 0, 1, "generic language/style container ",
          ["tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          nil,
          nil),
        ElemDesc.new("strike", 0, 3, 0, 0, 1, 1, 1, "strike-through text",
          ["tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          nil),
        ElemDesc.new("strong", 0, 3, 0, 0, 0, 0, 1, "strong emphasis",
          ["tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          nil,
          nil),
        ElemDesc.new("style", 0, 0, 0, 0, 0, 0, 0, "style info ",
          [].freeze, nil,
          ["lang", "dir", "media", "title"].freeze,
          nil,
          ["type"].freeze),
        ElemDesc.new("sub", 0, 3, 0, 0, 0, 0, 1, "subscript",
          ["tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          nil,
          nil),
        ElemDesc.new("sup", 0, 3, 0, 0, 0, 0, 1, "superscript ",
          ["tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          nil,
          nil),
        ElemDesc.new("table", 0, 0, 0, 0, 0, 0, 0, "",
          ["caption", "col", "colgroup", "thead", "tfoot", "tbody", "tr"].freeze, "tr",
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup", "summary", "width", "border", "frame", "rules", "cellspacing", "cellpadding", "datapagesize"].freeze,
          ["align", "bgcolor"].freeze,
          nil),
        ElemDesc.new("tbody", 1, 0, 0, 0, 0, 0, 0, "table body ",
          ["tr"].freeze, "tr",
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup", "align", "char", "charoff", "valign"].freeze,
          nil,
          nil),
        ElemDesc.new("td", 0, 0, 0, 0, 0, 0, 0, "table data cell",
          ["h1", "h2", "h3", "h4", "h5", "h6", "ul", "ol", "dir", "menu", "pre", "p", "dl", "div", "center", "noscript", "noframes", "blockquote", "form", "isindex", "hr", "table", "fieldset", "address", "tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup", "abbr", "axis", "headers", "scope", "rowspan", "colspan", "align", "char", "charoff", "valign"].freeze,
          ["nowrap", "bgcolor", "width", "height"].freeze,
          nil),
        ElemDesc.new("textarea", 0, 0, 0, 0, 0, 0, 1, "multi-line text field ",
          [].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup", "name", "disabled", "readonly", "tabindex", "accesskey", "onfocus", "onblur", "onselect", "onchange"].freeze,
          nil,
          ["rows", "cols"].freeze),
        ElemDesc.new("tfoot", 0, 1, 0, 0, 0, 0, 0, "table footer ",
          ["tr"].freeze, "tr",
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup", "align", "char", "charoff", "valign"].freeze,
          nil,
          nil),
        ElemDesc.new("th", 0, 1, 0, 0, 0, 0, 0, "table header cell",
          ["h1", "h2", "h3", "h4", "h5", "h6", "ul", "ol", "dir", "menu", "pre", "p", "dl", "div", "center", "noscript", "noframes", "blockquote", "form", "isindex", "hr", "table", "fieldset", "address", "tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup", "abbr", "axis", "headers", "scope", "rowspan", "colspan", "align", "char", "charoff", "valign"].freeze,
          ["nowrap", "bgcolor", "width", "height"].freeze,
          nil),
        ElemDesc.new("thead", 0, 1, 0, 0, 0, 0, 0, "table header ",
          ["tr"].freeze, "tr",
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup", "align", "char", "charoff", "valign"].freeze,
          nil,
          nil),
        ElemDesc.new("title", 0, 0, 0, 0, 0, 0, 0, "document title ",
          [].freeze, nil,
          ["lang", "dir"].freeze,
          nil,
          nil),
        ElemDesc.new("tr", 0, 0, 0, 0, 0, 0, 0, "table row ",
          ["th", "td"].freeze, "td",
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup", "align", "char", "charoff", "valign"].freeze,
          ["bgcolor"].freeze,
          nil),
        ElemDesc.new("tt", 0, 3, 0, 0, 0, 0, 1, "teletype or monospaced text style",
          ["tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          nil,
          nil),
        ElemDesc.new("u", 0, 3, 0, 0, 1, 1, 1, "underlined text style",
          ["tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          nil),
        ElemDesc.new("ul", 0, 0, 0, 0, 0, 0, 0, "unordered list ",
          ["li"].freeze, "li",
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          ["type", "compact"].freeze,
          nil),
        ElemDesc.new("var", 0, 0, 0, 0, 0, 0, 1, "instance of a variable or program argument",
          ["tt", "i", "b", "u", "s", "strike", "big", "small", "em", "strong", "dfn", "code", "samp", "kbd", "var", "cite", "abbr", "acronym", "a", "img", "applet", "embed", "object", "font", "basefont", "br", "script", "map", "q", "sub", "sup", "span", "bdo", "iframe", "input", "select", "textarea", "label", "button"].freeze, nil,
          ["id", "class", "style", "title", "lang", "dir", "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmouseout", "onkeypress", "onkeydown", "onkeyup"].freeze,
          nil,
          nil),
      ].freeze
  
      START_CLOSE = [
        ["a", "a"],
        ["a", "fieldset"],
        ["a", "table"],
        ["a", "td"],
        ["a", "th"],
        ["address", "dd"],
        ["address", "dl"],
        ["address", "dt"],
        ["address", "form"],
        ["address", "li"],
        ["address", "ul"],
        ["b", "center"],
        ["b", "p"],
        ["b", "td"],
        ["b", "th"],
        ["big", "p"],
        ["caption", "col"],
        ["caption", "colgroup"],
        ["caption", "tbody"],
        ["caption", "tfoot"],
        ["caption", "thead"],
        ["caption", "tr"],
        ["col", "col"],
        ["col", "colgroup"],
        ["col", "tbody"],
        ["col", "tfoot"],
        ["col", "thead"],
        ["col", "tr"],
        ["colgroup", "colgroup"],
        ["colgroup", "tbody"],
        ["colgroup", "tfoot"],
        ["colgroup", "thead"],
        ["colgroup", "tr"],
        ["dd", "dt"],
        ["dir", "dd"],
        ["dir", "dl"],
        ["dir", "dt"],
        ["dir", "form"],
        ["dir", "ul"],
        ["dl", "form"],
        ["dl", "li"],
        ["dt", "dd"],
        ["dt", "dl"],
        ["font", "center"],
        ["font", "td"],
        ["font", "th"],
        ["form", "form"],
        ["h1", "fieldset"],
        ["h1", "form"],
        ["h1", "li"],
        ["h1", "p"],
        ["h1", "table"],
        ["h2", "fieldset"],
        ["h2", "form"],
        ["h2", "li"],
        ["h2", "p"],
        ["h2", "table"],
        ["h3", "fieldset"],
        ["h3", "form"],
        ["h3", "li"],
        ["h3", "p"],
        ["h3", "table"],
        ["h4", "fieldset"],
        ["h4", "form"],
        ["h4", "li"],
        ["h4", "p"],
        ["h4", "table"],
        ["h5", "fieldset"],
        ["h5", "form"],
        ["h5", "li"],
        ["h5", "p"],
        ["h5", "table"],
        ["h6", "fieldset"],
        ["h6", "form"],
        ["h6", "li"],
        ["h6", "p"],
        ["h6", "table"],
        ["head", "a"],
        ["head", "abbr"],
        ["head", "acronym"],
        ["head", "address"],
        ["head", "b"],
        ["head", "bdo"],
        ["head", "big"],
        ["head", "blockquote"],
        ["head", "body"],
        ["head", "br"],
        ["head", "center"],
        ["head", "cite"],
        ["head", "code"],
        ["head", "dd"],
        ["head", "dfn"],
        ["head", "dir"],
        ["head", "div"],
        ["head", "dl"],
        ["head", "dt"],
        ["head", "em"],
        ["head", "fieldset"],
        ["head", "font"],
        ["head", "form"],
        ["head", "frameset"],
        ["head", "h1"],
        ["head", "h2"],
        ["head", "h3"],
        ["head", "h4"],
        ["head", "h5"],
        ["head", "h6"],
        ["head", "hr"],
        ["head", "i"],
        ["head", "iframe"],
        ["head", "img"],
        ["head", "kbd"],
        ["head", "li"],
        ["head", "listing"],
        ["head", "map"],
        ["head", "menu"],
        ["head", "ol"],
        ["head", "p"],
        ["head", "pre"],
        ["head", "q"],
        ["head", "s"],
        ["head", "samp"],
        ["head", "small"],
        ["head", "span"],
        ["head", "strike"],
        ["head", "strong"],
        ["head", "sub"],
        ["head", "sup"],
        ["head", "table"],
        ["head", "tt"],
        ["head", "u"],
        ["head", "ul"],
        ["head", "var"],
        ["head", "xmp"],
        ["hr", "form"],
        ["i", "center"],
        ["i", "p"],
        ["i", "td"],
        ["i", "th"],
        ["legend", "fieldset"],
        ["li", "li"],
        ["link", "body"],
        ["link", "frameset"],
        ["listing", "dd"],
        ["listing", "dl"],
        ["listing", "dt"],
        ["listing", "fieldset"],
        ["listing", "form"],
        ["listing", "li"],
        ["listing", "table"],
        ["listing", "ul"],
        ["menu", "dd"],
        ["menu", "dl"],
        ["menu", "dt"],
        ["menu", "form"],
        ["menu", "ul"],
        ["ol", "form"],
        ["option", "optgroup"],
        ["option", "option"],
        ["p", "address"],
        ["p", "blockquote"],
        ["p", "body"],
        ["p", "caption"],
        ["p", "center"],
        ["p", "col"],
        ["p", "colgroup"],
        ["p", "dd"],
        ["p", "dir"],
        ["p", "div"],
        ["p", "dl"],
        ["p", "dt"],
        ["p", "fieldset"],
        ["p", "form"],
        ["p", "frameset"],
        ["p", "h1"],
        ["p", "h2"],
        ["p", "h3"],
        ["p", "h4"],
        ["p", "h5"],
        ["p", "h6"],
        ["p", "head"],
        ["p", "hr"],
        ["p", "li"],
        ["p", "listing"],
        ["p", "menu"],
        ["p", "ol"],
        ["p", "p"],
        ["p", "pre"],
        ["p", "table"],
        ["p", "tbody"],
        ["p", "td"],
        ["p", "tfoot"],
        ["p", "th"],
        ["p", "title"],
        ["p", "tr"],
        ["p", "ul"],
        ["p", "xmp"],
        ["pre", "dd"],
        ["pre", "dl"],
        ["pre", "dt"],
        ["pre", "fieldset"],
        ["pre", "form"],
        ["pre", "li"],
        ["pre", "table"],
        ["pre", "ul"],
        ["s", "p"],
        ["script", "noscript"],
        ["small", "p"],
        ["span", "td"],
        ["span", "th"],
        ["strike", "p"],
        ["style", "body"],
        ["style", "frameset"],
        ["tbody", "tbody"],
        ["tbody", "tfoot"],
        ["td", "tbody"],
        ["td", "td"],
        ["td", "tfoot"],
        ["td", "th"],
        ["td", "tr"],
        ["tfoot", "tbody"],
        ["th", "tbody"],
        ["th", "td"],
        ["th", "tfoot"],
        ["th", "th"],
        ["th", "tr"],
        ["thead", "tbody"],
        ["thead", "tfoot"],
        ["title", "body"],
        ["title", "frameset"],
        ["tr", "tbody"],
        ["tr", "tfoot"],
        ["tr", "tr"],
        ["tt", "p"],
        ["u", "p"],
        ["u", "td"],
        ["u", "th"],
        ["ul", "address"],
        ["ul", "form"],
        ["ul", "menu"],
        ["ul", "pre"],
        ["xmp", "dd"],
        ["xmp", "dl"],
        ["xmp", "dt"],
        ["xmp", "fieldset"],
        ["xmp", "form"],
        ["xmp", "li"],
        ["xmp", "table"],
        ["xmp", "ul"],
      ].freeze
  
      ENTITIES_TABLE = [
        EntityDesc.new(34, "quot", "quotation mark = APL quote, U+0022 ISOnum"),
        EntityDesc.new(38, "amp", "ampersand, U+0026 ISOnum"),
        EntityDesc.new(39, "apos", "single quote"),
        EntityDesc.new(60, "lt", "less-than sign, U+003C ISOnum"),
        EntityDesc.new(62, "gt", "greater-than sign, U+003E ISOnum"),
        EntityDesc.new(160, "nbsp", "no-break space = non-breaking space, U+00A0 ISOnum"),
        EntityDesc.new(161, "iexcl", "inverted exclamation mark, U+00A1 ISOnum"),
        EntityDesc.new(162, "cent", "cent sign, U+00A2 ISOnum"),
        EntityDesc.new(163, "pound", "pound sign, U+00A3 ISOnum"),
        EntityDesc.new(164, "curren", "currency sign, U+00A4 ISOnum"),
        EntityDesc.new(165, "yen", "yen sign = yuan sign, U+00A5 ISOnum"),
        EntityDesc.new(166, "brvbar", "broken bar = broken vertical bar, U+00A6 ISOnum"),
        EntityDesc.new(167, "sect", "section sign, U+00A7 ISOnum"),
        EntityDesc.new(168, "uml", "diaeresis = spacing diaeresis, U+00A8 ISOdia"),
        EntityDesc.new(169, "copy", "copyright sign, U+00A9 ISOnum"),
        EntityDesc.new(170, "ordf", "feminine ordinal indicator, U+00AA ISOnum"),
        EntityDesc.new(171, "laquo", "left-pointing double angle quotation mark = left pointing guillemet, U+00AB ISOnum"),
        EntityDesc.new(172, "not", "not sign, U+00AC ISOnum"),
        EntityDesc.new(173, "shy", "soft hyphen = discretionary hyphen, U+00AD ISOnum"),
        EntityDesc.new(174, "reg", "registered sign = registered trade mark sign, U+00AE ISOnum"),
        EntityDesc.new(175, "macr", "macron = spacing macron = overline = APL overbar, U+00AF ISOdia"),
        EntityDesc.new(176, "deg", "degree sign, U+00B0 ISOnum"),
        EntityDesc.new(177, "plusmn", "plus-minus sign = plus-or-minus sign, U+00B1 ISOnum"),
        EntityDesc.new(178, "sup2", "superscript two = superscript digit two = squared, U+00B2 ISOnum"),
        EntityDesc.new(179, "sup3", "superscript three = superscript digit three = cubed, U+00B3 ISOnum"),
        EntityDesc.new(180, "acute", "acute accent = spacing acute, U+00B4 ISOdia"),
        EntityDesc.new(181, "micro", "micro sign, U+00B5 ISOnum"),
        EntityDesc.new(182, "para", "pilcrow sign = paragraph sign, U+00B6 ISOnum"),
        EntityDesc.new(183, "middot", "middle dot = Georgian comma Greek middle dot, U+00B7 ISOnum"),
        EntityDesc.new(184, "cedil", "cedilla = spacing cedilla, U+00B8 ISOdia"),
        EntityDesc.new(185, "sup1", "superscript one = superscript digit one, U+00B9 ISOnum"),
        EntityDesc.new(186, "ordm", "masculine ordinal indicator, U+00BA ISOnum"),
        EntityDesc.new(187, "raquo", "right-pointing double angle quotation mark right pointing guillemet, U+00BB ISOnum"),
        EntityDesc.new(188, "frac14", "vulgar fraction one quarter = fraction one quarter, U+00BC ISOnum"),
        EntityDesc.new(189, "frac12", "vulgar fraction one half = fraction one half, U+00BD ISOnum"),
        EntityDesc.new(190, "frac34", "vulgar fraction three quarters = fraction three quarters, U+00BE ISOnum"),
        EntityDesc.new(191, "iquest", "inverted question mark = turned question mark, U+00BF ISOnum"),
        EntityDesc.new(192, "Agrave", "latin capital letter A with grave = latin capital letter A grave, U+00C0 ISOlat1"),
        EntityDesc.new(193, "Aacute", "latin capital letter A with acute, U+00C1 ISOlat1"),
        EntityDesc.new(194, "Acirc", "latin capital letter A with circumflex, U+00C2 ISOlat1"),
        EntityDesc.new(195, "Atilde", "latin capital letter A with tilde, U+00C3 ISOlat1"),
        EntityDesc.new(196, "Auml", "latin capital letter A with diaeresis, U+00C4 ISOlat1"),
        EntityDesc.new(197, "Aring", "latin capital letter A with ring above = latin capital letter A ring, U+00C5 ISOlat1"),
        EntityDesc.new(198, "AElig", "latin capital letter AE = latin capital ligature AE, U+00C6 ISOlat1"),
        EntityDesc.new(199, "Ccedil", "latin capital letter C with cedilla, U+00C7 ISOlat1"),
        EntityDesc.new(200, "Egrave", "latin capital letter E with grave, U+00C8 ISOlat1"),
        EntityDesc.new(201, "Eacute", "latin capital letter E with acute, U+00C9 ISOlat1"),
        EntityDesc.new(202, "Ecirc", "latin capital letter E with circumflex, U+00CA ISOlat1"),
        EntityDesc.new(203, "Euml", "latin capital letter E with diaeresis, U+00CB ISOlat1"),
        EntityDesc.new(204, "Igrave", "latin capital letter I with grave, U+00CC ISOlat1"),
        EntityDesc.new(205, "Iacute", "latin capital letter I with acute, U+00CD ISOlat1"),
        EntityDesc.new(206, "Icirc", "latin capital letter I with circumflex, U+00CE ISOlat1"),
        EntityDesc.new(207, "Iuml", "latin capital letter I with diaeresis, U+00CF ISOlat1"),
        EntityDesc.new(208, "ETH", "latin capital letter ETH, U+00D0 ISOlat1"),
        EntityDesc.new(209, "Ntilde", "latin capital letter N with tilde, U+00D1 ISOlat1"),
        EntityDesc.new(210, "Ograve", "latin capital letter O with grave, U+00D2 ISOlat1"),
        EntityDesc.new(211, "Oacute", "latin capital letter O with acute, U+00D3 ISOlat1"),
        EntityDesc.new(212, "Ocirc", "latin capital letter O with circumflex, U+00D4 ISOlat1"),
        EntityDesc.new(213, "Otilde", "latin capital letter O with tilde, U+00D5 ISOlat1"),
        EntityDesc.new(214, "Ouml", "latin capital letter O with diaeresis, U+00D6 ISOlat1"),
        EntityDesc.new(215, "times", "multiplication sign, U+00D7 ISOnum"),
        EntityDesc.new(216, "Oslash", "latin capital letter O with stroke latin capital letter O slash, U+00D8 ISOlat1"),
        EntityDesc.new(217, "Ugrave", "latin capital letter U with grave, U+00D9 ISOlat1"),
        EntityDesc.new(218, "Uacute", "latin capital letter U with acute, U+00DA ISOlat1"),
        EntityDesc.new(219, "Ucirc", "latin capital letter U with circumflex, U+00DB ISOlat1"),
        EntityDesc.new(220, "Uuml", "latin capital letter U with diaeresis, U+00DC ISOlat1"),
        EntityDesc.new(221, "Yacute", "latin capital letter Y with acute, U+00DD ISOlat1"),
        EntityDesc.new(222, "THORN", "latin capital letter THORN, U+00DE ISOlat1"),
        EntityDesc.new(223, "szlig", "latin small letter sharp s = ess-zed, U+00DF ISOlat1"),
        EntityDesc.new(224, "agrave", "latin small letter a with grave = latin small letter a grave, U+00E0 ISOlat1"),
        EntityDesc.new(225, "aacute", "latin small letter a with acute, U+00E1 ISOlat1"),
        EntityDesc.new(226, "acirc", "latin small letter a with circumflex, U+00E2 ISOlat1"),
        EntityDesc.new(227, "atilde", "latin small letter a with tilde, U+00E3 ISOlat1"),
        EntityDesc.new(228, "auml", "latin small letter a with diaeresis, U+00E4 ISOlat1"),
        EntityDesc.new(229, "aring", "latin small letter a with ring above = latin small letter a ring, U+00E5 ISOlat1"),
        EntityDesc.new(230, "aelig", "latin small letter ae = latin small ligature ae, U+00E6 ISOlat1"),
        EntityDesc.new(231, "ccedil", "latin small letter c with cedilla, U+00E7 ISOlat1"),
        EntityDesc.new(232, "egrave", "latin small letter e with grave, U+00E8 ISOlat1"),
        EntityDesc.new(233, "eacute", "latin small letter e with acute, U+00E9 ISOlat1"),
        EntityDesc.new(234, "ecirc", "latin small letter e with circumflex, U+00EA ISOlat1"),
        EntityDesc.new(235, "euml", "latin small letter e with diaeresis, U+00EB ISOlat1"),
        EntityDesc.new(236, "igrave", "latin small letter i with grave, U+00EC ISOlat1"),
        EntityDesc.new(237, "iacute", "latin small letter i with acute, U+00ED ISOlat1"),
        EntityDesc.new(238, "icirc", "latin small letter i with circumflex, U+00EE ISOlat1"),
        EntityDesc.new(239, "iuml", "latin small letter i with diaeresis, U+00EF ISOlat1"),
        EntityDesc.new(240, "eth", "latin small letter eth, U+00F0 ISOlat1"),
        EntityDesc.new(241, "ntilde", "latin small letter n with tilde, U+00F1 ISOlat1"),
        EntityDesc.new(242, "ograve", "latin small letter o with grave, U+00F2 ISOlat1"),
        EntityDesc.new(243, "oacute", "latin small letter o with acute, U+00F3 ISOlat1"),
        EntityDesc.new(244, "ocirc", "latin small letter o with circumflex, U+00F4 ISOlat1"),
        EntityDesc.new(245, "otilde", "latin small letter o with tilde, U+00F5 ISOlat1"),
        EntityDesc.new(246, "ouml", "latin small letter o with diaeresis, U+00F6 ISOlat1"),
        EntityDesc.new(247, "divide", "division sign, U+00F7 ISOnum"),
        EntityDesc.new(248, "oslash", "latin small letter o with stroke, = latin small letter o slash, U+00F8 ISOlat1"),
        EntityDesc.new(249, "ugrave", "latin small letter u with grave, U+00F9 ISOlat1"),
        EntityDesc.new(250, "uacute", "latin small letter u with acute, U+00FA ISOlat1"),
        EntityDesc.new(251, "ucirc", "latin small letter u with circumflex, U+00FB ISOlat1"),
        EntityDesc.new(252, "uuml", "latin small letter u with diaeresis, U+00FC ISOlat1"),
        EntityDesc.new(253, "yacute", "latin small letter y with acute, U+00FD ISOlat1"),
        EntityDesc.new(254, "thorn", "latin small letter thorn with, U+00FE ISOlat1"),
        EntityDesc.new(255, "yuml", "latin small letter y with diaeresis, U+00FF ISOlat1"),
        EntityDesc.new(338, "OElig", "latin capital ligature OE, U+0152 ISOlat2"),
        EntityDesc.new(339, "oelig", "latin small ligature oe, U+0153 ISOlat2"),
        EntityDesc.new(352, "Scaron", "latin capital letter S with caron, U+0160 ISOlat2"),
        EntityDesc.new(353, "scaron", "latin small letter s with caron, U+0161 ISOlat2"),
        EntityDesc.new(376, "Yuml", "latin capital letter Y with diaeresis, U+0178 ISOlat2"),
        EntityDesc.new(402, "fnof", "latin small f with hook = function = florin, U+0192 ISOtech"),
        EntityDesc.new(710, "circ", "modifier letter circumflex accent, U+02C6 ISOpub"),
        EntityDesc.new(732, "tilde", "small tilde, U+02DC ISOdia"),
        EntityDesc.new(913, "Alpha", "greek capital letter alpha, U+0391"),
        EntityDesc.new(914, "Beta", "greek capital letter beta, U+0392"),
        EntityDesc.new(915, "Gamma", "greek capital letter gamma, U+0393 ISOgrk3"),
        EntityDesc.new(916, "Delta", "greek capital letter delta, U+0394 ISOgrk3"),
        EntityDesc.new(917, "Epsilon", "greek capital letter epsilon, U+0395"),
        EntityDesc.new(918, "Zeta", "greek capital letter zeta, U+0396"),
        EntityDesc.new(919, "Eta", "greek capital letter eta, U+0397"),
        EntityDesc.new(920, "Theta", "greek capital letter theta, U+0398 ISOgrk3"),
        EntityDesc.new(921, "Iota", "greek capital letter iota, U+0399"),
        EntityDesc.new(922, "Kappa", "greek capital letter kappa, U+039A"),
        EntityDesc.new(923, "Lambda", "greek capital letter lambda, U+039B ISOgrk3"),
        EntityDesc.new(924, "Mu", "greek capital letter mu, U+039C"),
        EntityDesc.new(925, "Nu", "greek capital letter nu, U+039D"),
        EntityDesc.new(926, "Xi", "greek capital letter xi, U+039E ISOgrk3"),
        EntityDesc.new(927, "Omicron", "greek capital letter omicron, U+039F"),
        EntityDesc.new(928, "Pi", "greek capital letter pi, U+03A0 ISOgrk3"),
        EntityDesc.new(929, "Rho", "greek capital letter rho, U+03A1"),
        EntityDesc.new(931, "Sigma", "greek capital letter sigma, U+03A3 ISOgrk3"),
        EntityDesc.new(932, "Tau", "greek capital letter tau, U+03A4"),
        EntityDesc.new(933, "Upsilon", "greek capital letter upsilon, U+03A5 ISOgrk3"),
        EntityDesc.new(934, "Phi", "greek capital letter phi, U+03A6 ISOgrk3"),
        EntityDesc.new(935, "Chi", "greek capital letter chi, U+03A7"),
        EntityDesc.new(936, "Psi", "greek capital letter psi, U+03A8 ISOgrk3"),
        EntityDesc.new(937, "Omega", "greek capital letter omega, U+03A9 ISOgrk3"),
        EntityDesc.new(945, "alpha", "greek small letter alpha, U+03B1 ISOgrk3"),
        EntityDesc.new(946, "beta", "greek small letter beta, U+03B2 ISOgrk3"),
        EntityDesc.new(947, "gamma", "greek small letter gamma, U+03B3 ISOgrk3"),
        EntityDesc.new(948, "delta", "greek small letter delta, U+03B4 ISOgrk3"),
        EntityDesc.new(949, "epsilon", "greek small letter epsilon, U+03B5 ISOgrk3"),
        EntityDesc.new(950, "zeta", "greek small letter zeta, U+03B6 ISOgrk3"),
        EntityDesc.new(951, "eta", "greek small letter eta, U+03B7 ISOgrk3"),
        EntityDesc.new(952, "theta", "greek small letter theta, U+03B8 ISOgrk3"),
        EntityDesc.new(953, "iota", "greek small letter iota, U+03B9 ISOgrk3"),
        EntityDesc.new(954, "kappa", "greek small letter kappa, U+03BA ISOgrk3"),
        EntityDesc.new(955, "lambda", "greek small letter lambda, U+03BB ISOgrk3"),
        EntityDesc.new(956, "mu", "greek small letter mu, U+03BC ISOgrk3"),
        EntityDesc.new(957, "nu", "greek small letter nu, U+03BD ISOgrk3"),
        EntityDesc.new(958, "xi", "greek small letter xi, U+03BE ISOgrk3"),
        EntityDesc.new(959, "omicron", "greek small letter omicron, U+03BF NEW"),
        EntityDesc.new(960, "pi", "greek small letter pi, U+03C0 ISOgrk3"),
        EntityDesc.new(961, "rho", "greek small letter rho, U+03C1 ISOgrk3"),
        EntityDesc.new(962, "sigmaf", "greek small letter final sigma, U+03C2 ISOgrk3"),
        EntityDesc.new(963, "sigma", "greek small letter sigma, U+03C3 ISOgrk3"),
        EntityDesc.new(964, "tau", "greek small letter tau, U+03C4 ISOgrk3"),
        EntityDesc.new(965, "upsilon", "greek small letter upsilon, U+03C5 ISOgrk3"),
        EntityDesc.new(966, "phi", "greek small letter phi, U+03C6 ISOgrk3"),
        EntityDesc.new(967, "chi", "greek small letter chi, U+03C7 ISOgrk3"),
        EntityDesc.new(968, "psi", "greek small letter psi, U+03C8 ISOgrk3"),
        EntityDesc.new(969, "omega", "greek small letter omega, U+03C9 ISOgrk3"),
        EntityDesc.new(977, "thetasym", "greek small letter theta symbol, U+03D1 NEW"),
        EntityDesc.new(978, "upsih", "greek upsilon with hook symbol, U+03D2 NEW"),
        EntityDesc.new(982, "piv", "greek pi symbol, U+03D6 ISOgrk3"),
        EntityDesc.new(8194, "ensp", "en space, U+2002 ISOpub"),
        EntityDesc.new(8195, "emsp", "em space, U+2003 ISOpub"),
        EntityDesc.new(8201, "thinsp", "thin space, U+2009 ISOpub"),
        EntityDesc.new(8204, "zwnj", "zero width non-joiner, U+200C NEW RFC 2070"),
        EntityDesc.new(8205, "zwj", "zero width joiner, U+200D NEW RFC 2070"),
        EntityDesc.new(8206, "lrm", "left-to-right mark, U+200E NEW RFC 2070"),
        EntityDesc.new(8207, "rlm", "right-to-left mark, U+200F NEW RFC 2070"),
        EntityDesc.new(8211, "ndash", "en dash, U+2013 ISOpub"),
        EntityDesc.new(8212, "mdash", "em dash, U+2014 ISOpub"),
        EntityDesc.new(8216, "lsquo", "left single quotation mark, U+2018 ISOnum"),
        EntityDesc.new(8217, "rsquo", "right single quotation mark, U+2019 ISOnum"),
        EntityDesc.new(8218, "sbquo", "single low-9 quotation mark, U+201A NEW"),
        EntityDesc.new(8220, "ldquo", "left double quotation mark, U+201C ISOnum"),
        EntityDesc.new(8221, "rdquo", "right double quotation mark, U+201D ISOnum"),
        EntityDesc.new(8222, "bdquo", "double low-9 quotation mark, U+201E NEW"),
        EntityDesc.new(8224, "dagger", "dagger, U+2020 ISOpub"),
        EntityDesc.new(8225, "Dagger", "double dagger, U+2021 ISOpub"),
        EntityDesc.new(8226, "bull", "bullet = black small circle, U+2022 ISOpub"),
        EntityDesc.new(8230, "hellip", "horizontal ellipsis = three dot leader, U+2026 ISOpub"),
        EntityDesc.new(8240, "permil", "per mille sign, U+2030 ISOtech"),
        EntityDesc.new(8242, "prime", "prime = minutes = feet, U+2032 ISOtech"),
        EntityDesc.new(8243, "Prime", "double prime = seconds = inches, U+2033 ISOtech"),
        EntityDesc.new(8249, "lsaquo", "single left-pointing angle quotation mark, U+2039 ISO proposed"),
        EntityDesc.new(8250, "rsaquo", "single right-pointing angle quotation mark, U+203A ISO proposed"),
        EntityDesc.new(8254, "oline", "overline = spacing overscore, U+203E NEW"),
        EntityDesc.new(8260, "frasl", "fraction slash, U+2044 NEW"),
        EntityDesc.new(8364, "euro", "euro sign, U+20AC NEW"),
        EntityDesc.new(8465, "image", "blackletter capital I = imaginary part, U+2111 ISOamso"),
        EntityDesc.new(8472, "weierp", "script capital P = power set = Weierstrass p, U+2118 ISOamso"),
        EntityDesc.new(8476, "real", "blackletter capital R = real part symbol, U+211C ISOamso"),
        EntityDesc.new(8482, "trade", "trade mark sign, U+2122 ISOnum"),
        EntityDesc.new(8501, "alefsym", "alef symbol = first transfinite cardinal, U+2135 NEW"),
        EntityDesc.new(8592, "larr", "leftwards arrow, U+2190 ISOnum"),
        EntityDesc.new(8593, "uarr", "upwards arrow, U+2191 ISOnum"),
        EntityDesc.new(8594, "rarr", "rightwards arrow, U+2192 ISOnum"),
        EntityDesc.new(8595, "darr", "downwards arrow, U+2193 ISOnum"),
        EntityDesc.new(8596, "harr", "left right arrow, U+2194 ISOamsa"),
        EntityDesc.new(8629, "crarr", "downwards arrow with corner leftwards = carriage return, U+21B5 NEW"),
        EntityDesc.new(8656, "lArr", "leftwards double arrow, U+21D0 ISOtech"),
        EntityDesc.new(8657, "uArr", "upwards double arrow, U+21D1 ISOamsa"),
        EntityDesc.new(8658, "rArr", "rightwards double arrow, U+21D2 ISOtech"),
        EntityDesc.new(8659, "dArr", "downwards double arrow, U+21D3 ISOamsa"),
        EntityDesc.new(8660, "hArr", "left right double arrow, U+21D4 ISOamsa"),
        EntityDesc.new(8704, "forall", "for all, U+2200 ISOtech"),
        EntityDesc.new(8706, "part", "partial differential, U+2202 ISOtech"),
        EntityDesc.new(8707, "exist", "there exists, U+2203 ISOtech"),
        EntityDesc.new(8709, "empty", "empty set = null set = diameter, U+2205 ISOamso"),
        EntityDesc.new(8711, "nabla", "nabla = backward difference, U+2207 ISOtech"),
        EntityDesc.new(8712, "isin", "element of, U+2208 ISOtech"),
        EntityDesc.new(8713, "notin", "not an element of, U+2209 ISOtech"),
        EntityDesc.new(8715, "ni", "contains as member, U+220B ISOtech"),
        EntityDesc.new(8719, "prod", "n-ary product = product sign, U+220F ISOamsb"),
        EntityDesc.new(8721, "sum", "n-ary summation, U+2211 ISOamsb"),
        EntityDesc.new(8722, "minus", "minus sign, U+2212 ISOtech"),
        EntityDesc.new(8727, "lowast", "asterisk operator, U+2217 ISOtech"),
        EntityDesc.new(8730, "radic", "square root = radical sign, U+221A ISOtech"),
        EntityDesc.new(8733, "prop", "proportional to, U+221D ISOtech"),
        EntityDesc.new(8734, "infin", "infinity, U+221E ISOtech"),
        EntityDesc.new(8736, "ang", "angle, U+2220 ISOamso"),
        EntityDesc.new(8743, "and", "logical and = wedge, U+2227 ISOtech"),
        EntityDesc.new(8744, "or", "logical or = vee, U+2228 ISOtech"),
        EntityDesc.new(8745, "cap", "intersection = cap, U+2229 ISOtech"),
        EntityDesc.new(8746, "cup", "union = cup, U+222A ISOtech"),
        EntityDesc.new(8747, "int", "integral, U+222B ISOtech"),
        EntityDesc.new(8756, "there4", "therefore, U+2234 ISOtech"),
        EntityDesc.new(8764, "sim", "tilde operator = varies with = similar to, U+223C ISOtech"),
        EntityDesc.new(8773, "cong", "approximately equal to, U+2245 ISOtech"),
        EntityDesc.new(8776, "asymp", "almost equal to = asymptotic to, U+2248 ISOamsr"),
        EntityDesc.new(8800, "ne", "not equal to, U+2260 ISOtech"),
        EntityDesc.new(8801, "equiv", "identical to, U+2261 ISOtech"),
        EntityDesc.new(8804, "le", "less-than or equal to, U+2264 ISOtech"),
        EntityDesc.new(8805, "ge", "greater-than or equal to, U+2265 ISOtech"),
        EntityDesc.new(8834, "sub", "subset of, U+2282 ISOtech"),
        EntityDesc.new(8835, "sup", "superset of, U+2283 ISOtech"),
        EntityDesc.new(8836, "nsub", "not a subset of, U+2284 ISOamsn"),
        EntityDesc.new(8838, "sube", "subset of or equal to, U+2286 ISOtech"),
        EntityDesc.new(8839, "supe", "superset of or equal to, U+2287 ISOtech"),
        EntityDesc.new(8853, "oplus", "circled plus = direct sum, U+2295 ISOamsb"),
        EntityDesc.new(8855, "otimes", "circled times = vector product, U+2297 ISOamsb"),
        EntityDesc.new(8869, "perp", "up tack = orthogonal to = perpendicular, U+22A5 ISOtech"),
        EntityDesc.new(8901, "sdot", "dot operator, U+22C5 ISOamsb"),
        EntityDesc.new(8968, "lceil", "left ceiling = apl upstile, U+2308 ISOamsc"),
        EntityDesc.new(8969, "rceil", "right ceiling, U+2309 ISOamsc"),
        EntityDesc.new(8970, "lfloor", "left floor = apl downstile, U+230A ISOamsc"),
        EntityDesc.new(8971, "rfloor", "right floor, U+230B ISOamsc"),
        EntityDesc.new(9001, "lang", "left-pointing angle bracket = bra, U+2329 ISOtech"),
        EntityDesc.new(9002, "rang", "right-pointing angle bracket = ket, U+232A ISOtech"),
        EntityDesc.new(9674, "loz", "lozenge, U+25CA ISOpub"),
        EntityDesc.new(9824, "spades", "black spade suit, U+2660 ISOpub"),
        EntityDesc.new(9827, "clubs", "black club suit = shamrock, U+2663 ISOpub"),
        EntityDesc.new(9829, "hearts", "black heart suit = valentine, U+2665 ISOpub"),
        EntityDesc.new(9830, "diams", "black diamond suit, U+2666 ISOpub"),
      ].freeze

      # start tags that imply the end of current element, keyed "old\0new" (htmlCheckAutoClose)
      START_CLOSE_SET = START_CLOSE.each_with_object({}) { |(o, n), h| h["#{o}\0#{n}"] = true }.freeze

      # htmlNoContentElements
      NO_CONTENT_ELEMENTS = ["html", "head"].freeze

      # htmlScriptAttributes
      SCRIPT_ATTRIBUTES = [
        "onclick", "ondblclick", "onmousedown", "onmouseup", "onmouseover", "onmousemove",
        "onmouseout", "onkeypress", "onkeydown", "onkeyup", "onload", "onunload", "onfocus",
        "onblur", "onsubmit", "onreset", "onchange", "onselect",
      ].freeze

      # htmlEndPriority (default 100)
      END_PRIORITY = {
        "div" => 150, "td" => 160, "th" => 160, "tr" => 170, "thead" => 180, "tbody" => 180,
        "tfoot" => 180, "table" => 190, "head" => 200, "body" => 200, "html" => 220,
      }.freeze

      # allowPCData
      ALLOW_PCDATA = [
        "a", "abbr", "acronym", "address", "applet", "b", "bdo", "big",
        "blockquote", "body", "button", "caption", "center", "cite", "code",
        "dd", "del", "dfn", "div", "dt", "em", "font", "form", "h1", "h2",
        "h3", "h4", "h5", "h6", "i", "iframe", "ins", "kbd", "label", "legend",
        "li", "noframes", "noscript", "object", "p", "pre", "q", "s", "samp",
        "small", "span", "strike", "strong", "td", "th", "tt", "u", "var",
      ].freeze

      ENTITY_BY_NAME = {}.tap do |h|
        ENTITIES_TABLE.each { |e| h[e.name] ||= e }
      end.freeze

      TAG_CACHE = {} # rubocop:disable Style/MutableConstant

      module_function

      # xmlStrcasecmp over bytes (casemap only folds ASCII A-Z)
      def strcasecmp(a, b)
        a = a.b
        b = b.b
        i = 0
        loop do
          ca = a.getbyte(i) || 0
          cb = b.getbyte(i) || 0
          ca += 32 if ca >= 65 && ca <= 90
          cb += 32 if cb >= 65 && cb <= 90
          tmp = ca - cb
          return tmp if tmp != 0
          return 0 if cb == 0

          i += 1
        end
      end

      # htmlTagLookup (bsearch with xmlStrcasecmp over html40ElementTable)
      def tag_lookup(tag)
        return nil if tag.nil?

        tag = tag.to_s
        return TAG_CACHE[tag] if TAG_CACHE.key?(tag)

        key = tag.include?("\0") ? tag[0, tag.index("\0")] : tag
        lo = 0
        hi = ELEMENT_TABLE.length
        found = nil
        while lo < hi
          mid = (lo + hi) / 2
          c = strcasecmp(key, ELEMENT_TABLE[mid].name)
          if c < 0
            hi = mid
          elsif c > 0
            lo = mid + 1
          else
            found = ELEMENT_TABLE[mid]
            break
          end
        end
        TAG_CACHE[tag.frozen? ? tag : tag.dup.freeze] = found if TAG_CACHE.size < 10_000
        found
      end

      # htmlEntityLookup (linear, case-sensitive)
      def entity_lookup(name)
        return nil if name.nil?

        ENTITY_BY_NAME[name.to_s]
      end

      # htmlEntityValueLookup (bsearch by codepoint)
      def entity_value_lookup(value)
        lo = 0
        hi = ENTITIES_TABLE.length
        while lo < hi
          mid = (lo + hi) / 2
          c = value - ENTITIES_TABLE[mid].value
          if c < 0
            hi = mid
          elsif c > 0
            lo = mid + 1
          else
            return ENTITIES_TABLE[mid]
          end
        end
        nil
      end

      # htmlCheckAutoClose: does +newtag+ implicitly close +oldtag+?
      def check_auto_close(newtag, oldtag)
        START_CLOSE_SET.key?("#{oldtag}\0#{newtag}")
      end

      # htmlGetEndPriority
      def get_end_priority(name)
        END_PRIORITY.fetch(name, 100)
      end

      # htmlIsScriptAttribute
      def script_attribute?(name)
        return false if name.nil?
        return false unless name.start_with?("on")

        SCRIPT_ATTRIBUTES.include?(name)
      end

      # htmlAutoCloseTag
      def auto_close_tag(doc, name, elem)
        return true if elem.nil?
        return false if name == elem.name
        return true if check_auto_close(elem.name, name)

        child = elem.children
        while child
          return true if auto_close_tag(doc, name, child)

          child = child.next
        end
        false
      end

      # htmlIsAutoClosed
      def auto_closed?(doc, elem)
        return true if elem.nil?

        child = elem.children
        while child
          return true if auto_close_tag(doc, elem.name, child)

          child = child.next
        end
        false
      end
    end
  end
end
